### Numpy Array Operations

In [2]:
import numpy as np

### Slicing

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing : ", arr[1:8])
print("With Step : ", arr[1:8:2])
print("Negative indexing : ", arr[-3])

Basic slicing :  [2 3 4 5 6 7 8]
With Step :  [2 4 6 8]
Negative indexing :  8


In [14]:
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Specific Element : ", arr_2d[1,2])
print("Specific Row :", arr_2d[1])
print("Slicing : \n", arr_2d[0:3])
print("Slicing with step : \n", arr_2d[0:3:2])
print("Specific column :", arr_2d[:,0])
print("Slicing with column : \n", arr_2d[0:2, 1]) # arr_2d(rows,columns)
print("Slicing with column : \n", arr_2d[0:2, 0:2]) # arr_2d(rows,columns)

Specific Element :  6
Specific Row : [4 5 6]
Slicing : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing with step : 
 [[1 2 3]
 [7 8 9]]
Specific column : [1 4 7]
Slicing with column : 
 [2 5]
Slicing with column : 
 [[1 2]
 [4 5]]


### Sorting 

In [18]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array : ", np.sort(unsorted))

arr_2d_unsorted = np.array([[8, 1], [5, 4], [2, 3]])
print("Sorted 2D array by column :\n", np.sort(arr_2d_unsorted, axis=0)) 
print("Sorted 2D array by Row :\n", np.sort(arr_2d_unsorted, axis=1)) 

Sorted Array :  [1 1 2 3 4 5 6 9]
Sorted 2D array by column :
 [[2 1]
 [5 3]
 [8 4]]
Sorted 2D array by Row :
 [[1 8]
 [4 5]
 [2 3]]


### Filtering 

In [19]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even = numbers[numbers%2 == 0]
print("Even numbers : ", even)

Even numbers :  [ 2  4  6  8 10]


### Filtering with Masking

In [20]:
mask = numbers > 5
print("Numbers greater than 5 : ", numbers[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [23]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
# print(where_result) # (array([5, 6, 7, 8, 9]),)
print("Numbers greater than 5 : ", numbers[where_result])

[1 3 5]
Numbers greater than 5 :  [ 6  7  8  9 10]


In [24]:
condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Stacking

In [8]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print("Original :\n", original)
print("Vertical Stack (Adds row) :\n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("Horizontal stack (Add Column) :\n", with_new_col)

Original :
 [[1 2]
 [3 4]]
Vertical Stack (Adds row) :
 [[1 2]
 [3 4]
 [5 6]]
Horizontal stack (Add Column) :
 [[1 2 7]
 [3 4 8]]


### Array element deletion 

In [9]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
