### Numpy Level 1

In [1]:
import numpy as np
import time

In [2]:
arr_1d = np.array([1,2,3,4,5]) # np.array(list as parameter)
# arr_2d = np.array([1,2,3],[4,5,6]) # Error
arr_2d = np.array([[1,2,3],[4,5,6]])
print("Array 1D:\n",arr_1d)
print("Array 2D:\n",arr_2d)

Array 1D:
 [1 2 3 4 5]
Array 2D:
 [[1 2 3]
 [4 5 6]]


### List vs Numpy With Speed Test

In [ ]:
py_list = [1,2,3] * 2
# print (py_list) # [1, 2, 3, 1, 2, 3]
np_list = [1,2,3] * 2
# print (np_list) # [2,4,6] elementwise operation

# speed test
start = time.time()
py_list = [i*2 for i in range(1000000)] # like [2,4,6,8 ......]
print("Operation time Using pytho List : ", time.time() - start)

start = time.time()
np_list = np.arange(1000000) * 2 # like [2,4,6,8 ......]
print("Operation time Using Numpy Array : ", time.time() - start)

Operation time Using pytho List :  0.07618355751037598
Operation time Using Numpy Array :  0.0037865638732910156


### Creating Numpy Arrays From Scratch 

In [10]:
zeros = np.zeros((3,3))
print("Zero Array :\n",zeros)
ones = np.ones((2,3))
print("One Array :\n",ones)
full = np.full((3,3),7)
print("Full Array :\n",full)
random = np.random.random((3,3))
print("Random Array :\n",random)

Zero Array :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
One Array :
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array :
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random Array :
 [[0.580993   0.62195959 0.1925271 ]
 [0.3253056  0.50662108 0.28344543]
 [0.29926732 0.659549   0.54252983]]


### What are Vectors , Matrix and Tensor

In [ ]:
vector = np.array([1,2,3,4,5,6]) # This is called as vector or 1d array

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]) # This is called matrix or 2d array

tensor = np.array([

    [
        [1,2,3],
        [4,5,6]
    ],

    [
        [7,8,9],
        [10,11,12]
    ]
]) # This is called Tensor(An Array with more than 2 dimension, in this example it is 3d array)

print("Vector :\n", vector)
print("Matrix :\n", matrix)
print("Tensor :\n", tensor)

Vector :
 [1 2 3 4 5 6]
Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],
                [3,4,5]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Data type: int64


### Array Reshaping

In [26]:
arr = np.arange(1,11)
print("Original Array : ",arr)

reshaped = arr.reshape((2,5))
print("Reshaped Array : \n",reshaped)
reshaped = arr.reshape((5,2))
print("Reshaped Array : \n",reshaped)
# reshaped = arr.reshape((3,3)) # Error, 3x3=9, we have 10 elements

flatten = arr.flatten()
print("Flatten Array : ",flatten)


# raveled = reshaped.ravel() # ravel (returns view, instead of copy)
# print("raveled array : \n", raveled)

# Transpose
transpose = reshaped.T
print("Transposed array : \n", transpose)


Original Array :  [ 1  2  3  4  5  6  7  8  9 10]
Reshaped Array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reshaped Array : 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Flatten Array :  [ 1  2  3  4  5  6  7  8  9 10]
Transposed array : 
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
